CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "AdminUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PasswordHash" text NOT NULL,
        "PasswordSalt" text NOT NULL,
        "Iterations" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AdminUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "GalleryItems" (
        "Id" text NOT NULL,
        "Title" jsonb NOT NULL,
        "Category" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "Position" text NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_GalleryItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "Locations" (
        "Id" text NOT NULL,
        "Area" text NOT NULL,
        "Address" jsonb NOT NULL,
        "Phone" text NOT NULL,
        "Coordinates" text NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "Services" (
        "Id" text NOT NULL,
        "Name" jsonb NOT NULL,
        "Description" jsonb NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "SiteMedia" (
        "Key" text NOT NULL,
        "Url" text NOT NULL,
        CONSTRAINT "PK_SiteMedia" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "SiteSettings" (
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        CONSTRAINT "PK_SiteSettings" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "SiteStates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SiteStates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    CREATE TABLE "SiteTexts" (
        "Language" text NOT NULL,
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        CONSTRAINT "PK_SiteTexts" PRIMARY KEY ("Language", "Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    INSERT INTO "SiteStates" ("Id", "UpdatedAt")
    VALUES (1, TIMESTAMPTZ '2026-09-10T20:21:20.765335+00:00');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SiteStates"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SiteStates") + 1,
            nextval(pg_get_serial_sequence('"SiteStates"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910202121_InitialPostgresSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260910202121_InitialPostgresSchema', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911152718_AddBookings') THEN
    CREATE TABLE "Bookings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Phone" text NOT NULL,
        "Studio" text NOT NULL,
        "Service" text NOT NULL,
        "Date" date NOT NULL,
        "Time" time without time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911152718_AddBookings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911152718_AddBookings', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911153457_AddBookingReferences') THEN
    ALTER TABLE "Bookings" ADD "ServiceId" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911153457_AddBookingReferences') THEN
    ALTER TABLE "Bookings" ADD "StudioId" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911153457_AddBookingReferences') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911153457_AddBookingReferences', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911154011_AddBookingManagement') THEN
    ALTER TABLE "Bookings" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911154011_AddBookingManagement') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911154011_AddBookingManagement', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915161929_AddCategoriesAndServiceGrouping') THEN
    ALTER TABLE "Services" ADD "CategoryId" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915161929_AddCategoriesAndServiceGrouping') THEN
    ALTER TABLE "Services" ADD "GroupLabel" jsonb NOT NULL DEFAULT ('{}'::jsonb);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915161929_AddCategoriesAndServiceGrouping') THEN
    ALTER TABLE "Services" ADD "SubgroupLabel" jsonb NOT NULL DEFAULT ('{}'::jsonb);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915161929_AddCategoriesAndServiceGrouping') THEN
    CREATE TABLE "Categories" (
        "Id" text NOT NULL,
        "Name" jsonb NOT NULL,
        "ImageUrl" text NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915161929_AddCategoriesAndServiceGrouping') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260915161929_AddCategoriesAndServiceGrouping', '10.0.12');
    END IF;
END $EF$;
COMMIT;

